-- MySQL Script generated by MySQL Workbench
-- Fri Jan 21 15:57:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8 ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`DOCTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`DOCTORS` (
  `DOC_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DOC_SNAME` VARCHAR(45) NOT NULL,
  `DOC_FNAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DOC_ID`),
  INDEX `DOC_SNAME` (`DOC_SNAME` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`PATIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`PATIENTS` (
  `PAT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `PAT_SNAME` VARCHAR(45) NOT NULL,
  `PAT_FNAME` VARCHAR(45) NOT NULL,
  `DOCTORS_DOC_ID` INT(11) NOT NULL,
  PRIMARY KEY (`PAT_ID`),
  INDEX `PAT_SNAME` (`PAT_SNAME` ASC) VISIBLE,
  INDEX `fk_PATIENTS_DOCTORS_idx` (`DOCTORS_DOC_ID` ASC) VISIBLE,
  UNIQUE INDEX `PAT_ID_UNIQUE` (`PAT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PATIENTS_DOCTORS`
    FOREIGN KEY (`DOCTORS_DOC_ID`)
    REFERENCES `hospital`.`DOCTORS` (`DOC_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`USERLIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`USERLIST` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
